name: Sandbox â€“ Build Windows Installer (No Prod Impact)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - ci-sandbox

permissions:
  contents: read

jobs:
  build-windows-sandbox:
    runs-on: windows-latest   #only windows produces .exe and not Ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip/setuptools/wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller playsound3 sacremoses tokenizers importlib-metadata

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --noconsole --onedir ^
            --copy-metadata tqdm ^
            --copy-metadata regex ^
            --copy-metadata sacremoses ^
            --copy-metadata requests ^
            --copy-metadata packaging ^
            --copy-metadata filelock ^
            --copy-metadata tokenizers ^
            --copy-metadata importlib_metadata ^
            --collect-data sv_ttk ^
            --hidden-import "babel.numbers" ^
            --add-data "shared/images/*;shared/images" ^
            --add-data "shared/sounds/*;shared/sounds" ^
            --add-data "settings;settings" ^
            main.py

      - name: Rename EXE
        run: ren dist\main\main.exe Mouser.exe

      - name: Zip artifact
        run: powershell Compress-Archive -Path dist/main/* -DestinationPath dist/Mouser_windows-latest.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mouser_windows-latest
          path: dist/Mouser_windows-latest.zip
          if-no-files-found: error
