name: Build Mouser Windows Executable

on:
  workflow_dispatch:       # allows manual runs
  pull_request:            # runs on PR
  push:                    # runs on pushes to main
    branches: [ main ]

jobs:
  build-windows:
    uses: ./.github/workflows/build-reusable.yml
    with: {}